# Generated by Django 4.1.6 on 2023-02-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_searchhall'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstaff',
            name='Department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addstaff',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
