# Generated by Django 4.1.6 on 2023-02-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addstaff_department_alter_addstaff_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStaffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AddStaff',
        ),
    ]
