# Generated by Django 4.1.6 on 2023-02-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_addstaffs_delete_addstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Hallname', models.CharField(max_length=30)),
                ('NumberofAttendees', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('NameofEvent', models.CharField(max_length=30)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('is_projector', models.BooleanField(default=False)),
                ('is_Mic', models.BooleanField(default=False)),
                ('is_Internet', models.BooleanField(default=False)),
                ('is_Lamp', models.BooleanField(default=False)),
                ('otherRequest', models.CharField(max_length=30)),
            ],
        ),
    ]
