# Generated by Django 4.1.6 on 2023-02-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hallbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallbook',
            old_name='is_Lamp',
            new_name='Internet',
        ),
        migrations.RenameField(
            model_name='hallbook',
            old_name='is_Internet',
            new_name='Lamp',
        ),
        migrations.RenameField(
            model_name='hallbook',
            old_name='is_Mic',
            new_name='Mic',
        ),
        migrations.RenameField(
            model_name='hallbook',
            old_name='is_projector',
            new_name='projector',
        ),
    ]
