# Generated by Django 4.1.6 on 2023-02-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_is_lamp_hallbook_internet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallbook',
            name='Internet',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='hallbook',
            name='Lamp',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='hallbook',
            name='Mic',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='hallbook',
            name='projector',
            field=models.BooleanField(),
        ),
    ]
