# Generated by Django 4.1.6 on 2023-02-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_hallbook_internet_alter_hallbook_lamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHall',
        ),
    ]
