# Generated by Django 4.1.6 on 2023-02-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_searchhall'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Hallname', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
    ]
