# Generated by Django 4.1.6 on 2023-03-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_hallbook_internet_remove_hallbook_lamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallbook',
            name='Equipments',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
