# Generated by Django 4.1.6 on 2023-03-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_searchhall_endtime_searchhall_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhall',
            name='EndTime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='searchhall',
            name='StartTime',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
