# Generated by Django 4.1.6 on 2023-03-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_searchhall_endtime_alter_searchhall_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Feedback', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='hallbook',
            name='EndTime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hallbook',
            name='StartTime',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
